### ISSUE TITLE
Blob não acaba depois de ter dominado parte da estação

### ISSUE THREAD

**Issue by astralenigma** [nopm/Beat-Station#100]
**Descrição do problema**:
Qual é o problema?
Quando o blob atinge o número esperado de quadrados o jogo não lhe dá a vitória.
**O que você esperava que acontecece**: 
O que era para acontecer?
Acabar o jogo e dar vitória ao blob.
**O que ocorreu**:
O que aconteceu no lugar?
O jogo continuou e foi necessário reiniciar o servidor.
**Por quê você acha que isso é ruim?**
Por quê isso deveria ser consertado?
O modo de jogo está quebrado é preciso outra razão?
**Como reproduzir o problema**:
A parte mais importante. Conte o que fazer para que o problema ocorra novamente.

**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, etc):** Qualquer coisa que possa nos contar.
Secret-Blob

**Comment by nopm** [comment]
UAHSUAHSUSHUASHAUSHAUSH, @astralenigma Astral meu amor, fui eu que configurei pro round não acabar em gamemodes que ele acaba sem a shuttle.

**Comment by astralenigma** [comment]
@nopm sabes que isso faz com que um jogo fique preso infinitamente não sabes?

**Comment by nopm** [comment]
Não, só chamar a shuttle. Os poucos casos que isso ocorreu foi por intervenção dos admns (minha) de chamar a shuttle devolta. @astralenigma

**Comment by astralenigma** [comment]
Uma das vezes em que fiquei sozinho no servidor a shuttle foi chamada mas como havia blob deu erro e por isso a shuttle não partiu.
E eu tive de reiniciar o servidor.

**Comment by davipatury** [comment]
Ué

**Comment by nopm** [comment]
@davipatury Testando o webhook.

**Comment by davipatury** [comment]
Atá.

**Comment by astralenigma** [comment]
Fica fechado por agora.
