### ISSUE TITLE
Scrubber do janitor

### ISSUE THREAD

**Issue by astralenigma** [nopm/Beat-Station#11]
**Descrição do problema**:
Qual é o problema?
O scrubber do Janitor não está conectado ao waste
**O que você esperava que acontecece**: 
O que era para acontecer?
O scrubber devia estar conectado ao loop.
**O que ocorreu**:
O que aconteceu no lugar?
Faltam pipes.
**Por quê você acha que isso é ruim?**
Por quê isso deveria ser consertado?
Se isso não estiver não dá para limpar o ar nessa zona.
Também dá problemas para quem usa o scrubber loop para navegar como aliens e swarmers.
**Como reproduzir o problema**:
A parte mais importante. Conte o que fazer para que o problema ocorra novamente.
Levantar o chão e ver.
**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, etc):** Qualquer coisa que possa nos contar.
Parece me um bom trabalho para os mapas.

**Comment by nopm** [comment]
Vou chamar o Itus.

**Comment by davipatury** [comment]
http://prntscr.com/bk9b17

**Comment by davipatury** [comment]
![Imagem da desconexão](http://image.prntscr.com/image/e30049d04d554eaf82cf602a24444dcf.png)

**Comment by davipatury** [comment]
[https://github.com/nopm/Beat-Station/pull/12](url)

**Comment by nopm** [comment]
O Davi arrumou o problema, vou fechar por enquanto.

**Comment by astralenigma** [comment]
@nopm O davi voltou a criar esse problema.

**Comment by davipatury** [comment]
@astralenigma eu já desfiz a merda
