### ISSUE TITLE
Bug de runtime das cameras

### ISSUE THREAD

**Issue by astralenigma** [nopm/Beat-Station#134]
**Descrição do problema**:
Por alguma razão o Dream Seeker borra-se todo quando tenta mostrar as câmeras da Space Station.

**O que você esperava que acontecece**: 
Conseguir usar as cameras.

**O que ocorreu**:
Crashou o Dream Seeker duas vezes da primeira vez que ativei as câmeras e da segunda vez quando tentei abrir a consola.

**Por quê você acha que isso é ruim?**
...

**Como reproduzir o problema**:
Cliquei no botão do SS13 na consola de cameras do spec ops officer.

**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, etc):**
...

**Comment by davipatury** [comment]
#258 fixed.
