### ISSUE TITLE
Shadowling não leva dano da luz

### ISSUE THREAD

**Issue by kaseio** [nopm/Beat-Station#144]
**Descrição do problema**:
O shadowling não leva dano da luz.
**O que você esperava que acontecece**: 
Ele levar dano.
**O que ocorreu**:
Nada.
**Por quê você acha que isso é ruim?**
Fica muito OP.
**Como reproduzir o problema**:
Virar shadowling.
**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, etc):**
S H A D O W L I N G. Provavelmente é um conflito com a dynamic light.

**Comment by davipatury** [comment]
Tenho quase certeza que não é conflito com dynamic light.
