### ISSUE TITLE
Não consigo salvar os personagens que crio

### ISSUE THREAD

**Issue by theo272727** [nopm/Beat-Station#151]
**Descrição do problema**:
Tento salvar um personagem novo que eu crio,mas ele não salva

**O que você esperava que acontecece**:
Que o personagem que criei seja salvo

**O que ocorreu**:
Nada.

**Por quê você acha que isso é ruim?**
Pois não posso criar outros personagens,limitado apenas dois (antes do bug)

**Como reproduzir o problema**:
Dou load em um slot vazio,crio o personagem,tento salvar o personagem,e ele não é salvo

**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, etc):** 
Me falaram que tem algo haver com a database (pois acho que foi resetada)

**Comment by davipatury** [comment]
Talvez o #139 resolva

**Comment by theo272727** [comment]
quando vão arrumar?

**Comment by davipatury** [comment]
Quando eu descobrir o que causa o problema.
