### ISSUE TITLE
Bebidas invisíveis

### ISSUE THREAD

**Issue by Introzado** [nopm/Beat-Station#165]
**Descrição do problema**:
Algumas bebidas estão ficando invisíveis, sem icon

**O que você esperava que acontecece**: 
Que elas tivessem um icon

**O que ocorreu**
Eu fui fazer bebidas nas máquinas do bar e algumas bebidas estão saindo invisíveis

**Por quê você acha que isso é ruim?**
Porque não da pra ver as bebidas

**Como reproduzir o problema**:
Fazendo algumas bebidas no bar

**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, etc):**
Algumas prints do bug

![a](http://image.prntscr.com/image/b06ff12dac40445b9793d8835c5951c7.png)
![b](http://image.prntscr.com/image/6ab51660e9ca43559243740b207f2352.png)

**Comment by itus2k** [comment]
nao deve ser bug de sprite
provavelmente e um bug no code

**Comment by kaseio** [comment]
Tá com bug no code provavelmente, tá tudo ficando invisível, como o stunprod..

**Comment by itus2k** [comment]
sim

**Comment by itus2k** [comment]
deve ser algo bobo

**Comment by davipatury** [comment]
Se o problema só ocorre com as tequillas é por que o cara que codou não sabe escrever `tequilla` com dois L.

**Comment by Yukkionechan** [comment]
Eita
