### ISSUE TITLE
Cult pode começar com menos de 3 cultistas

### ISSUE THREAD

**Issue by kaseio** [nopm/Beat-Station#172]
**Descrição do problema**:
Cult pode começar com menos de 3 cultistas

**O que você esperava que acontecece**: 
Cult pode começar com 3 ou mais cultistas

**O que ocorreu**:
Começa com apenas 1 ou 2 cultistas

**Por quê você acha que isso é ruim?**
O gamemode não pode continuar

**Como reproduzir o problema**:
Cair cult em Secret

**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, etc):**
SECRET

**Comment by nopm** [comment]
É por causa do `force_debug` nos defines. Com isso ativado, qualquer gamemode vai entrar em jogo, com mínimo de players ou não. Ativamos isso pois o servidor lowpop.

**Comment by davipatury** [comment]
Por ser inválido o Issue será fechado e caso necessário será reaberto.
