### ISSUE TITLE
ABNT

### ISSUE THREAD

**Issue by Introzado** [nopm/Beat-Station#194]
**Descrição do problema**:
Qual é o problema?
Code não suportando ABNT
**O que você esperava que acontecece**: 
O que era para acontecer?
Que suportasse ABNT como sempre suportou
**O que ocorreu**:
O que aconteceu no lugar?
Toda frase que possui ç ou qualquer acento não aparece
**Por quê você acha que isso é ruim?**
Por quê isso deveria ser consertado?
porque a maioria das palavras em português usam esses acentos
**Como reproduzir o problema**:
A parte mais importante. Conte o que fazer para que o problema ocorra novamente.
falar qualquer coisa que que possua acentos ou ç
**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, etc):** Qualquer coisa que possa nos contar.
isso ta acontecendo em todos os canais não só em ic

**Comment by nopm** [comment]
#195 Deve corrigir. Deixarei aberto para poder confirmar.

**Comment by nopm** [comment]
Corrigido.
