### ISSUE TITLE
Janelas em HTML nos consoles ficam sem conteúdo

### ISSUE THREAD

**Issue by nopm** [nopm/Beat-Station#2]
**Descrição do problema**
Aleatóriamente durante um round uma (ou todas) as telas que utilizam HTML para mostrar conteúdo (melhor exemplo seria o PDA e os consoles da Cargo Bay e dos Comms) some totalmente seu conteúdo, tornando-o permanentemente inutlizável.

**O que você esperava que ocorrese**: 
Para o console mostrar o conteúdo correto.

**O que aconteceu no lugar**:
O conteúdo some, tornando-o inutilizável

**Por que isso é um problema.**
Não poder pedir emitters pela Cargo quando há um blob é um sério problema.

**Passos para reproduzir o problema**:
Isso pode acontecer aleatóriamente, ou simplesmente não acontece.

**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, qualquer coisa):**

**Comment by astralenigma** [comment]
Pelo que eu percebi os cargo technicians não têm acesso à consola para ordenar coisas só o QM pode fazer isso, o PDA pode ser resolvido com um reset ao PDA. Enviado do meu telefone Huawei.-------- Mensagem original --------Assunto: [nopm/Beat-Station] Janelas em HTML nos consoles ficam sem conteúdo (#2)De: nopm Para: nopm/Beat-Station CC: Descrição do problema
Aleatóriamente durante um round uma (ou todas) as telas que utiliam HTML para mostrar conteúdo (melhor exemplo seria o PDA e os consoles da Cargo Bay e dos Comms) some totalmente seu conteúdo, tornando-o permanentemente inutlizável.

O que você esperava que ocorrese: 
Para o console mostrar o conteúdo correto.

O que aconteceu no lugar:
O conteúdo some, tornando-o inutilizável

Por que isso é um problema.
Não poder pedir emitters pela Cargo quando há um blob é um sério problema.

Passos para reproduzir o problema:
Isso pode acontecer aleatóriamente, ou simplesmente não acontece.

Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, qualquer coisa):

**Comment by davipatury** [comment]
https://www.reddit.com/r/SS13/comments/3tn40y/i_have_a_slight_issue_with_ss13byond_bug_a_black/?

**Comment by nopm** [comment]
Não aparenta ser um problema com ActiveX, eu tenho ele ativo no IE desde que instalei o Windows 10. O estranho é que isso acontece com todos do server.

**Comment by astralenigma** [comment]
Parece que é um problema antigo do byond de só aceitar teclado inglês.

**Comment by nopm** [comment]
Isso não acontecia antes @astralenigma , na real nunca aconteceu, só agora...

**Comment by davipatury** [comment]
O meu Pull Request pode resolver isso.

**Comment by nopm** [comment]
Se o fix do Davi corrigir eu fecho esse issue~

**Comment by nopm** [comment]
Ok, já dei merge. Bug corrigido provavelmente!
