### ISSUE TITLE
Onde eu coloco o meu report?

### ISSUE THREAD

**Issue by Lucaszecron** [nopm/Beat-Station#284]

**Comment by HarmonycStalker** [comment]
Tem sim

**Comment by HarmonycStalker** [comment]
Filho da puta, baixa discord e vem

**Comment by Lucaszecron** [comment]
oloco calma

**Comment by HarmonycStalker** [comment]
<3

**Comment by Lucaszecron** [comment]
esqueci de apagar o negoci
esses adm zoerio q fica lendo e julgano
q feio PS: puta q pariu servidor com secret mais longo do mundo

**Comment by Lucaszecron** [comment]
e querendo ou não fazendo o negocio aqui consegui suas atenções

**Comment by VitorThauma** [comment]
https://discord.gg/J6PN5

**Comment by HarmonycStalker** [comment]
ATA
