### ISSUE TITLE
species.dm incompleto.

### ISSUE THREAD

**Issue by Schwaglord** [Nopm/Beat-Station#285]
O erp/species.dm não bate com o tanto de species no jogo.

Acredito que era pra estar mais completo, até porquê o arquivo está incompleto e intocável há uns 10 meses atrás.

Não tem muita coisa a mais pra dizer mas tem esse print abaixo:
![species](https://user-images.githubusercontent.com/30198060/30000133-adb373fc-9037-11e7-8064-640f94e7c900.png)

**Comment by Nopm** [comment]
Esse repositório já é antigo.
Vou linkar o novo.
https://github.com/Beat-Station/Beat-Station

**Comment by davipatury** [comment]
Nesse arquivo só tem as espécies que sobrepõem os valores padrões, ou seja, se uma espécie não está aí, ela não tem genitais.
