### ISSUE TITLE
Controlo do github ineficiente!

### ISSUE THREAD

**Issue by astralenigma** [nopm/Beat-Station#34]
**Descrição do problema**:
Qual é o problema?
Vários updates foram feitos que quebraram coisas que tinhamos feito, porque ninguém viu o que foi feito.
**O que você esperava que acontecece**: 
O que era para acontecer?
Eu esperava que antes de um merge ser feito, esse mesmo fosse revisto para detectar incompatibilidades e erros.
**O que ocorreu**:
O que aconteceu no lugar?
Vários merges que tinhamos feito foram quebrados por merges que alteravam 500+ ficheiros.
**Por quê você acha que isso é ruim?**
Por quê isso deveria ser consertado?
Se isso não for consertado teremos de reparar os erros invés de os corrigir.

**Comment by nopm** [comment]
Se você tiver disposto a fazer isso, eu te coloco como maintainer.

**Comment by nopm** [comment]
@astralenigma
