### ISSUE TITLE
Vox Armalis não spawna com máscara na cara.

### ISSUE THREAD

**Issue by astralenigma** [nopm/Beat-Station#8]
**Descrição do problema**:
Qual é o problema?
Vox Armalis não entra no jogo com máscara para respirar na cara.

**O que você esperava que acontecece**: 
O que era para acontecer?
O oxigénio faz mal ao Vox Armalis logo seria de esperar que spawnasse com uma máscara na cara.
**O que ocorreu**:
O que aconteceu no lugar?
Spawnou com a máscara na mão.
**Por quê você acha que isso é ruim?**
Por quê isso deveria ser consertado?
Se ninguém prestar atenção ele morre por falta de energia.
**Como reproduzir o problema**:
A parte mais importante. Conte o que fazer para que o problema ocorra novamente.
Spawnar como vox armalis
**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, etc):** Qualquer coisa que possa nos contar.

**Comment by nopm** [comment]
Eu não sabia dessa. Vou tentar alterar o mob para spawnar ela com a máscara no slot correto.

**Comment by davipatury** [comment]
`H.equip_or_collect(new /obj/item/clothing/mask/breath/vox(H), slot_wear_mask)`

**Comment by nopm** [comment]
@davipatury Tenta ver se você consegue arrumar isso

**Comment by davipatury** [comment]
O que tá dando é: A máscara do Vox Armalis não cabe no Vox Armalis.

**Comment by davipatury** [comment]
Acho que o https://github.com/nopm/Beat-Station/pull/15 pode resolver.

**Comment by nopm** [comment]
Acho que já posso fechar esse issue, #15 já arrumou.
