### ISSUE TITLE
Opções do "Who" não funcionando

### ISSUE THREAD

**Issue by nopm** [nopm/Beat-Station#85]
**Descrição do problema**:
Qual é o problema?
Opções do "Who" verb não funcionam
**O que você esperava que acontecece**: 
O que era para acontecer?
Abrir a porra do painel.
**O que ocorreu**:
O que aconteceu no lugar?
Nada.
**Por quê você acha que isso é ruim?**
Por quê isso deveria ser consertado?
Pois eu tenho uma preguiça severa de usar o new player panel ao invés de clicar em "PP" no Who.
**Como reproduzir o problema**:
A parte mais importante. Conte o que fazer para que o problema ocorra novamente.
Clica no "Who", no "?" do lado do cara e clica em "PP"
**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, etc):** Qualquer coisa que possa nos contar.
http://prntscr.com/bztjjb

**Comment by astralenigma** [comment]
Acho que o erro foi no #65 ou no #64

**Comment by nopm** [comment]
@davipatury Fix it now, as this is more than urgent.

**Comment by davipatury** [comment]
#87

**Comment by astralenigma** [comment]
Corrigido com o revert #97
