### ISSUE TITLE
Botões do Targeting System faltando sprites para outros UI Styles

### ISSUE THREAD

**Issue by davipatury** [nopm/Beat-Station#88]
**Descrição do problema**:
Ao mudar o UI Style, Botões do Targeting System acabam ficando sem sprites. (só tem o sprite do midnight)

**O que você esperava que acontecessee**: 
Aparecer os sprites bonitinhos de acordo com a cor da UI Style.

**O que ocorreu**:
Não apareceu sprite algum, ficou vazio, impossibilitando o uso do targeting system em outras UI styles.

**Por que você acha que isso é ruim?**
Por que quem usa outras UI Styles vai ficar prejudicado.

**Como reproduzir o problema**:
Game Preferences->Clique em UI Style->Veja os botões do Targeting System sumir

![image](https://cloud.githubusercontent.com/assets/10660904/17277924/31680138-5725-11e6-95a9-a0252f5e4534.png)

**Qualquer coisa relacionada(Qual era o gamemode, se os admins tavam mexendo com eventos, etc):**
![image](https://cloud.githubusercontent.com/assets/10660904/17277927/4207d64e-5725-11e6-8b4a-ccc5b24fad02.png)

### A culpa é do Davi que só copiou os sprites do Midnight.

**Comment by nopm** [comment]
Consigo confirmar

**Comment by astralenigma** [comment]
retro
slimecore
operative
white 
São os que faltam
