### ISSUE TITLE
Partida começou bugada, pessoas ficaram no lobby.

### ISSUE THREAD

**Issue by davipatury** [nopm/Beat-Station#89]
**Descrição do problema**:
Partida começa bugada, pessoas ficam no lobby.

**O que você esperava que acontecece**: 
Eles serem teleportados para a estação e ocorrer tudo normalmente.

**O que ocorreu**:
Ficaram presos no lobby.

**Por quê você acha que isso é ruim?**
...

**Como reproduzir o problema**:
Não sei como reproduzir.

**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, etc):**

Gamemode era secret. Provavelmente é um bug com o Xeno mode.

![image](https://cloud.githubusercontent.com/assets/10660904/17278086/21c1591e-572a-11e6-817e-0796b1ffaffa.png)

![image](https://cdn.discordapp.com/attachments/176500153492963328/209358435182051329/unknown.png)

**Comment by astralenigma** [comment]
Eu culpo davi :smile:

**Comment by nopm** [comment]
"Runtime in xenos.dm" Isso já aconteceu quando eu dei force secret em xenos. É o gamemode que tá completamente bugado.
