### ISSUE TITLE
Vítimas do vampiro são "imortais"

### ISSUE THREAD

**Issue by astralenigma** [nopm/Beat-Station#92]
**Descrição do problema**:
As vítimas dos vampiros não morrem mas ficam num estado de estar constantemente a morrer.

**O que você esperava que acontecece**: 
Era suposto as vítimas morrerem uma vez e não spamarem emotes.

**O que ocorreu**:
Spam enorme que chateou vários admins e confundiu um vampiro.

**Por quê você acha que isso é ruim?**
O facto da vítima permanecer viva e chata é razão mais que suficiente.

**Como reproduzir o problema**:
Morder a vítima como vampiro até o spam começar.

**Qualquer coisa relacionada(Qual era o gamemode, se os admns tavam mechendo com eventos, etc):**
O modo de jogo era vampiro mas não me parece que tenha a haver com isso.
As vítimas do vampiro estavam SSD ou ficaram SSD depois.

**Comment by kaseio** [comment]
Isso não é bug de vampiro, uma vez quando eu tava de Chemist eu peguei o pun pun e a IV drip, e tirei todo o sangue dele. Ele começou a spammar também, isso ocorre quando a vítima fica sem sangue.
~~Mas eu dei uns soco nele e paro o spam~~

**Comment by davipatury** [comment]
#251 Fixed it

**Comment by davipatury** [comment]
#251 fixed it.
